### ISSUE TITLE
Hey after run i am getting this error can you tell me what is the issue

### ISSUE THREAD

**Issue by Shahid140050** [gustavo-villar-dev/like4like.org-bot#1]
Traceback (most recent call last):
  File "C:\Users\Shahid-A\Desktop\like4like.org-bot-main\like4likesbot.py", line 91, in <module>
    ed.open()
  File "C:\Users\Shahid-A\Desktop\like4like.org-bot-main\like4likesbot.py", line 14, in open
    usuario = bot.find_element_by_name("username")
AttributeError: 'WebDriver' object has no attribute 'find_element_by_name'

**Comment by 0xGUZ** [comment]
hey! what webdriver are you using? i used chromium, if you want to use another you may have to change the find element by name method to something like find by xml or find my tag
